language: node_js

node_js:
  - 0.10

# Use container-based Travis infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master

script:
  # Verify all builds actually work.
  - npm run-script build
  - ./node_modules/.bin/gulp build:dev
  - ./node_modules/.bin/gulp build:test
  # Run all checks.
  - ./node_modules/.bin/gulp check:ci:linux
  # Manually send coverage reports to coveralls.
  # - First client result
  # - Only server result
  - cat  "coverage/client/$(ls coverage/client | head -n 1)/lcov.info" "coverage/server/lcov.info" | ./node_modules/.bin/coveralls
