language: node_js

node_js:
  - 0.10
  - 0.12

# Use container-based Travis infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - master

script:
  # Build environment.
  - node --version
  - npm --version
  # Build and test.
  - npm run-script build
  - npm run-script check
  - node_modules/.bin/gulp build:all
  - node_modules/.bin/gulp check:ci:linux
  # Manually send coverage reports to coveralls.
  # - Aggregate client results
  # - Single server and func test results
  - ls coverage/client/*/lcov.info coverage/{server,func}/lcov.info | cat
  - cat coverage/client/*/lcov.info coverage/{server,func}/lcov.info | ./node_modules/.bin/coveralls
