language: node_js

node_js:
  - 0.10

os:
  - osx

before_install:
  # **OS X**
  # Likely unneeded: - brew update
  - brew install caskroom/cask/brew-cask
  - brew cask install google-chrome firefox
  #
  # **Linux**
  # GUI for real browsers.
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start

script:
  # Verify all builds actually work.
  - npm run-script build
  - ./node_modules/.bin/gulp build:all
  # Run all checks.
  - ./node_modules/.bin/gulp check:ci:osx
  # Manually send coverage reports to coveralls.
  # - First client result
  # - Only server result
  - cat  "coverage/client/$(ls coverage/client | head -n 1)/lcov.info" "coverage/server/lcov.info" | ./node_modules/.bin/coveralls
