environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install
  - npm -g install npm@next

build: off

test_script:
  # Build environment.
  - node --version
  - npm --version
  # Build and test.
  - npm run-script build
  - npm run-script check-win
  - node_modules\.bin\gulp build:all
  - node_modules\.bin\gulp check:ci:win
