environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  # Install and use local, modern NPM
  - npm install npm@next
  - node_modules\.bin\npm install
  - node_modules\.bin\npm install-selenium

build: off

branches:
  only:
    - master

test_script:
  # Build environment.
  - node --version
  - node_modules\.bin\npm --version
  # Build and test.
  - node_modules\.bin\npm run-script build
  - node_modules\.bin\npm run-script check
  - node_modules\.bin\gulp build:all
  - node_modules\.bin\gulp check:ci:win
